import React from 'react';
import "../styles/TermsOfUsePage.css"
 
const TermsOfUsePage = () => {
  return (
    <div className='Paragraph'>
      <h1>Terms of Use</h1>
      <h2>Terms And Condition</h2>

        <p>The Application/APP means Kings Cricket Live. The Application is owned and operated by us. You and Your means the person using, browsing or otherwise accessing any content or data on the Application, 
          or related mobile sites, Apps, APIs and widgets.</p>
        <br />
        <p>You acknowledge and agree that by using, browsing or otherwise accessing Our King's Cricket Live APP, You agree to
           be bound by the terms and conditions of use. You agree to ensure that any person who accesses Our APP on your behalf 
           abides by these Terms. You acknowledge that we provide use and access to our APP to you subject to these Terms and Conditions.</p>
        <br />
        <p>We reserve the right to change any of the Terms or conditions for using Our King's Cricket Live Application at any time 
          by publishing new terms or conditions. Your use of our Application constitutes acceptance of those terms and conditions. 
          Should You object to any of Our terms and conditions of use or other notices, Your sole option is to immediately cease
           Your use of Our Application.</p>
        <br />
        <p>Your use of information on our King's Cricket Live app including results, fixture lists, statistics, data, odds and figures
           posted at Your own risk. Other than as expressly set out in these Terms and to the extent permitted by law, we make no 
           warranty as to the accuracy or reliability of the information contained on Our publications including, but not limited to,
            any content or information generated by or on behalf of Us, and any Third Party Content.</p>
        <br />
        <h2>Intellectual Property</h2>

        <p>Unless indicated otherwise, all intellectual property is owned or licensed by Us. Subject to these Terms, You agree that
           You will not infringe Our intellectual property and will not modify, copy, republish, frame, distribute or communicate any 
           part of it or any information contained in it or otherwise use King's Cricket Live APP in a way which will infringe Our 
           intellectual property or other rights.</p>

        <h2>Privacy </h2>
        
        <p>You agree to comply with Our privacy policy, guidelines and statements as may be applicable from time to time, which 
          are incorporated into these Terms, and can be found at Privacy Policy.</p>
    </div>
  );
};

export default TermsOfUsePage;